#ifndef PREVIEWWIDGET_GLOBAL_H
#define PREVIEWWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PREVIEWWIDGET_LIBRARY)
#  define PREVIEWWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PREVIEWWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PREVIEWWIDGET_GLOBAL_H
